# +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
# | A list of Sorts v2 config.yml |
# +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
# NOTE: Change only if you know what you are doing!


# +-+-+-+-+-+-+-+-+-+-+-+
# | Pygame GUI Settings |
# +-+-+-+-+-+-+-+-+-+-+-+
# Changes the refresh rate of pygame
framerate: 60

# Pygame windows fills the entire screen
fullscreen: false

# Config size of pygame window (Only apply if not fullscreen)
scale: 0.6

# Uses lots of CPU in a busy loop to make sure that fps timing is more accurate
tick_busy: False


# +-+-+-+-+-+-+-+-+-+
# | Sounds Settings |
# +-+-+-+-+-+-+-+-+-+
sound:
    # Master volume for all effects
    effects: 1.0

    # Volume range from 0 to 1.0 inclusive, with 1.0 being the loudest
    button: 0.12
    background: 0.12


# +-+-+-+-+-+-+-+-+-+
# | Logger Settings |
# +-+-+-+-+-+-+-+-+-+
# CRITICAL -> 50
# ERROR -> 40
# WARNING -> 30
# INFO -> 20
# DEBUG -> 10
logging:
  # For console output
  console_level: 'all'

  # App activities logged in './Ratventure/logs/'
  file_level: 'DEBUG'

  # Number of logs to keep in logs folder
  keep_logs: 5